development:
  bucket: comidero-dev
  access_key_id: AKIAIUJHZ2SOVH6P4G5A
  secret_access_key: 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
production:
  bucket: comidero-pro
  access_key_id: AKIAIUJHZ2SOVH6P4G5A
  secret_access_key: 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
